---
title: "Validation Checks - Trees"
output: html_document
date: "2024-08-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r}
tip_data <- ltp$tip_data
gt <- bp$`growth temperature` |> 
    select(NCBI_ID, Attribute_value, Evidence)
gtTD <- left_join(tip_data, gt, by = c("taxid" = "NCBI_ID")) 
gtTD2 <- gtTD |> 
    filter(!is.na(order_taxid)) |> 
    filter(!is.na(Evidence)) |> 
    group_by(order_taxid, Evidence) |>
    count() |> 
    group_by(order_taxid) |> 
    mutate(total = sum(n)) |> 
    ungroup() 
```

```{r}
ord <- gtTD |> 
    filter(order_taxid == "112" | family_taxid == "126")
targetClade <- grep("\\b112\\b", tr$node.label, value = TRUE)
subTr <- extract.clade(tr, targetClade)
subTrLabels <- c(subTr$tip.label, subTr$node.label)



# match(subTrLabels, )


```

```{r}
ord2 <- rename(ord, id = tip_label)
dat2 <- select(ord2, id, Attr_val = Attribute_value)

p <- ggtree(subTr)  %<+% 
    ord2 

p <- p +
    geom_tippoint(
        mapping = aes(color = Evidence)
    )
    # scale_color_manual(
    #     values = c("blue", "red", "green"),
    #     na.value = NA
    # )
ggtree::facet_plot(
    p = p, mapping = aes(x = Attr_val, fill = Evidence),
    data = dat2, geom = geom_col, panel = "Temperature",
    orientation = 'y', width = 0.9
)

```
