---
title: "Validation Checks - Exploratory plots"
output: html_document
date: "2024-08-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(taxPPro)
library(readr)
library(dplyr)
library(bugphyzz)
library(purrr)
library(tidyr)
library(ggplot2)
library(ggrepel)
library(forcats)
library(ape)
library(ggtree)
source("scripts/fun.R")
```

Import validation results:

```{r load validation data}
valFname <- system.file(
    "extdata", "validation_summary.tsv", package = "bugphyzz", mustWork = TRUE
)
selectColsNum <- c(
    "physiology", "attribute", "r2_mean", "ltp_bp_phys", "ltp_bp_phys_per"
)
selectColsBin <- c(
    "physiology", "attribute", "mcc_mean", "ltp_bp_phys", "ltp_bp_phys_per"
)
selectColsMul <- c(
    "physiology", "attribute", "mcc_mean",  "ltp_bp", "ltp_bp_per",
    "ltp_bp_phys", "ltp_bp_phys_per"
)
attrMul <- c(
    "spore shape",
    "hemolysis",
    "arrangement",
    "biosafety level",
    "cogem pathogenicity rating",
    "aerophilicity",
    "gram stain",
    "shape"
)
attrBin <- c(
    "extreme environment",
    "host-associated",
    "animal pathogen",
    "antimicrobial sensitivity",
    "motility",
    "plant pathogenicity",
    "spore formation"
)
valDat <- valFname |>
    read_tsv(show_col_types = FALSE) |>
    filter(rank == "all") |> 
    mutate(physiology = tolower(physiology)) # COGEM most be lower case
valDatNum <- valDat |> 
    filter(method == "castor-ltp") |> 
    select(all_of(selectColsNum)) |> 
    select(-physiology) |> 
    rename(Attribute = attribute)
valDatBin <- valDat |> 
    filter(method == "phytools-ltp") |> 
    filter(physiology %in% attrBin) |> 
    select(all_of(selectColsBin)) |> 
    select(-physiology) |> 
    rename(Attribute = attribute)
valDatMulI <- valDat |> 
    filter(method == "phytools-ltp") |> 
    filter(physiology %in% attrMul) |> 
    select(all_of(selectColsMul)) |> 
    rename(Attribute = physiology, Attribute_value = attribute) |> 
    mutate(Attribute_value = paste0(Attribute, "|", Attribute_value))
valDatMulG <- valDatMulI |> 
    group_by(Attribute) |> 
    mutate(mcc_mean = mean(mcc_mean)) |> 
    ungroup() |> 
    select(
        Attribute = Attribute, mcc_mean, ltp_bp_phys, ltp_bp_phys_per
    ) |> 
    distinct()
```

Load phylogenetic data:

```{r load tree data}
ltp <- ltp()
tr <- ltp$tree
tipDat <- ltp$tip_data |> 
    # group_by(taxid) |>
    # mutate(n = n()) |>
    # ungroup() |>
    # filter(n == 1) |> 
    select(tip_label, taxid)
droppedTips <- nrow(ltp$tip_data) - nrow(tipDat)
message(
    ## This message is only relevant is the same taxid is assigned to two or
    ## more tips.
    "Only use tips mapped to a single taxid. ",
    droppedTips, " tips were dropped. ",
    nrow(tipDat), " tips were kept."
)
```

Get pairwise distance between closest neighboring tips:

```{r get pairwise distances}
distFname <- "files/close_tips_distance.tsv"
if (file.exists(distFname)) {
    closeTips <- readr::read_tsv(distFname, show_col_types = FALSE) |> 
        mutate_at(.vars = c("taxid1", "taxid2"), .funs = as.character)
} else {
    closeTips <- getClosestTips(tr)
    closeTips <- bind_rows(closeTips, .id = "tip1")
    closeTips <- closeTips |> 
        left_join(
            tipDat, by = c("tip1" = "tip_label"), relationship = "many-to-many"
        ) |> 
        rename(taxid1 = taxid) |> 
        left_join(
            tipDat, by = c("tip2" = "tip_label"), relationship = "many-to-many"
        ) |> 
        rename(taxid2 = taxid) |> 
        relocate(distance, .after = last_col()) |> 
        mutate_at(.vars = c("taxid1", "taxid2"), .funs = as.character)
    readr::write_tsv(x = closeTips, file = distFname, num_threads = 10)
}
## The number of rows can be higher than the number of tips in the tree.
## I'm allowing cases in which A tip can have the same minimum distance
## to another tip.
## I'm also allowing repetitions (taking A to B and B to A, for example)
dim(closeTips)
```

Import bugphyzz:

```{r import bugphyzz}
bp <- importBugphyzz(forceDownload = FALSE, v = 0) |> 
    map(~ mutate(.x, NCBI_ID = as.character(NCBI_ID)))
```

Create input tables:

```{r create tables, message=FALSE}
bpSub <- bp |>
    map(~{
        # dups <- unique(.x$NCBI_ID[which(duplicated(.x$NCBI_ID))])
        .x |> 
            filter(Evidence != "asr") |> # Remove ASR
            # filter(!NCBI_ID %in% dups) |> 
            select(NCBI_ID, Attribute, Attribute_value) |> 
            mutate(NCBI_ID = as.character(NCBI_ID)) |> 
            # left_join(tipDat, by = c("NCBI_ID" = "taxid")) |>
            # select(-NCBI_ID) |> 
            drop_na() |>
            as_tibble() |> 
            rename(taxid = NCBI_ID)
        
    }) 
tipsL <- map(bpSub, ~ {
    closeTips |> 
        left_join(
            .x, by = c("taxid1" = "taxid"), relationship = "many-to-many"
        ) |> 
        rename(tip1Attr = Attribute, tip1AttrVal = Attribute_value) |> 
        left_join(
            .x, by = c("taxid2" = "taxid"), relationship = "many-to-many"
        ) |> 
        rename(tip2Attr = Attribute, tip2AttrVal = Attribute_value) |> 
        drop_na() |> 
        as_tibble()
})
tipsNum <- tipsL[valDatNum$Attribute] |> 
    map(~ {
        .x |> 
            rename(Attribute = tip1Attr) |> 
            select(-tip2Attr) |> 
            mutate(diff = abs(tip1AttrVal - tip2AttrVal)) |> 
            left_join(valDatNum, by = "Attribute")
    }) |> 
    bind_rows()
tipsBin <- tipsL[attrBin] |> 
        map(~ {
            mutate(.x, TF = ifelse(tip1AttrVal == tip2AttrVal, "TRUE", "FALSE")) |> 
                rename(Attribute = tip1Attr) |>
                select(-tip2Attr) |> 
                left_join(valDatBin, by = "Attribute")
        }) |> 
    bind_rows()
tipsMulG <- tipsL[attrMul] |> 
        map(~ {
            mutate(.x, TF = ifelse(tip1AttrVal == tip2AttrVal, "TRUE", "FALSE")) |> 
                rename(Attribute = tip1Attr) |> 
                select(-tip2Attr) |> 
                left_join(valDatMulG, by = "Attribute")
        }) |> 
    bind_rows()

tipsMulI <- bpSub[attrMul] |> 
    imap(~ {
        annL <- split(.x, .x$Attribute_value) |> 
            map(\(y) pull(y, taxid))
        uniqLabs <- unique(unlist(annL, use.names = FALSE))
        ctSub <- closeTips |>
            filter(
                ## This ensures that only annotated tips are considered.
                taxid1 %in% uniqLabs & taxid2 %in% uniqLabs
        )
        names(annL) <- paste0(.y, "|", names(annL))
        for (i in seq_along(annL)) {
            annName <- names(annL)[i]
            colName1 <- paste0(annName, "_tip1")
            colName2 <- paste0(annName, "_tip2")
            ctSub[[colName1]] <- ctSub$taxid1 %in% annL[[i]]
            ctSub[[colName2]] <- ctSub$taxid2 %in% annL[[i]]
            ctSub[[annName]] <- paste0(ctSub[[colName1]], "|", ctSub[[colName2]])
        }
        return(ctSub)
    })
tipsMulI <- map(tipsMulI,  ~ {
    .x |>
        select(-matches("_tip\\d$")) |> 
        pivot_longer(
            names_to = "Attribute", values_to = "logical",
            cols = 6:last_col()
        ) |> 
        filter(logical != "FALSE|FALSE") |>
        arrange(Attribute, logical, distance) |>
        mutate(
            Attribute = forcats::fct_inorder(Attribute)
        ) |>
        mutate(
            grp = sub("\\|.*$", "", Attribute)
        ) |>
        mutate(
            logical = ifelse(grepl("FALSE", logical), "FALSE", "TRUE")
        ) |> 
        rename(
            Attribute = grp, Attribute_value = Attribute,
            TF = logical
        )
}) |> 
    bind_rows() |> 
    left_join(valDatMulI, by = c("Attribute", "Attribute_value"))
```

## EDA Numeric values

```{r numPlot Ntips vs Mean R2}
tipsNum |> 
    group_by(Attribute) |> 
    mutate(
        mean_dist = mean(distance),
        mean_diff = mean(diff)
    ) |> 
    ungroup() |> 
    select(
        Attribute, r2_mean, ltp_bp_phys, ltp_bp_phys_per, mean_dist, mean_diff
    ) |> 
    distinct() |>
    ggplot(aes(ltp_bp_phys_per, r2_mean)) +
    geom_point(aes(color = mean_dist)) +
    geom_text_repel(aes(label = Attribute)) +
    scale_x_continuous(labels = scales::comma) +
    scale_color_continuous(name = "Mean pairwise\ndistance") +
    labs(
        y = "Mean R2", x = "Annotated tips (%)"
    ) +
    theme_bw()
```

```{r numPlot dist boxplot}
tipsNum |> 
    mutate(Attribute = paste0(Attribute, " (", r2_mean, ")")) |> 
    arrange(r2_mean) |> 
    mutate(Attribute = fct_inorder(Attribute)) |> 
    ggplot(aes(Attribute, distance)) +
    geom_boxplot(aes(fill = ltp_bp_phys_per)) +
    scale_fill_viridis_c(name = "Annotated\ntips (%)", option = "C") +
    labs(
        y = "Pairwise distance"
    ) +
    theme_bw() +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1)
    )
```
```{r numPlot diff vs dist, fig.width=9}
tipsNum |> 
    mutate(Attribute = paste0(Attribute, " (", r2_mean, ")")) |> 
    ggplot(aes(distance, diff)) +
    geom_point(size = 0.2) +
    facet_wrap(~ Attribute, scales = "free") +
    geom_smooth(method = "glm", formula = y ~ x) +
    scale_y_continuous(labels = scales::comma) +
    labs(
        x = "Pairwise distance" , y = "Value difference"
    ) +
    theme_bw()
```

## EDA discrete values (Multisate - Global)

```{r}
sumMulG <- tipsMulG |> 
    group_by(Attribute, TF) |> 
    summarise(
        meanDist = mean(distance),
        medianDist = median(distance),
        nTF = length(TF),
        val = unique(mcc_mean),
        nTips = unique(ltp_bp_phys),
        perTips = unique(ltp_bp_phys_per)
    ) |> 
    ungroup() |> 
    pivot_wider(
        names_from = "TF", values_from = c("nTF", "meanDist", "medianDist")
    ) |> 
    mutate(TFrat = nTF_TRUE / nTF_FALSE) |> 
    mutate(TFratDist = meanDist_TRUE / meanDist_FALSE) |> 
    mutate(TFratDistMed = medianDist_TRUE / medianDist_FALSE)
```

```{r}
sumMulGp1 <- sumMulG |> 
    ggplot(aes(perTips, val)) +
    geom_smooth(method = "lm", formula = y ~ x) +
    geom_point(
        # aes(size = TFrat, color = TFratDistMed)
        aes(size = TFrat, color = medianDist_TRUE)
    ) +
    geom_text_repel(aes(label = Attribute)) +
    scale_x_continuous(labels = scales::comma) +
    scale_color_viridis_c(
        name = "Median distance\nof concordant annotations", option = "C"
    ) +
    scale_size_continuous(name = "T/F ratio") +
    labs(
        x = "Annotated tips (%)",
        y = "Global mean MCC"
    ) +
    theme_bw()
sumMulGp1
```

## EDA discrete values (Multisate - individual)

```{r}
x <- tipsMulI |> 
    group_by(Attribute, Attribute_value, TF) |> 
    summarise(
        meanDist = mean(distance),
        medianDist = median(distance),
        nTF = length(TF),
        val = unique(mcc_mean),
        nTips = unique(ltp_bp),
        perTips = unique(ltp_bp)
    ) |> 
    ungroup() |> 
    drop_na() |> 
    pivot_wider(
        names_from = "TF", values_from = c("nTF", "meanDist", "medianDist")
    ) |> 
    mutate(TFrat = nTF_TRUE / nTF_FALSE) |> 
    mutate(TFratDist = meanDist_TRUE / meanDist_FALSE) |> 
    mutate(TFratDistMed = medianDist_TRUE / medianDist_FALSE)
```


```{r}
x |> 
    ggplot(aes(nTips, val)) +
     geom_smooth(method = "lm", formula = y ~ x) +
    geom_point(
        # aes(size = TFrat, color = medianDist_TRUE)
    ) +
    geom_text_repel(
        aes(label = Attribute_value), size = 2.5
    ) +
    labs(
        x = "Number of annotated tips",
        y = "Mean Mathews Correlation Coefficient"
    ) +
    scale_color_viridis_c(
        name = "Median distance\nof concordant annotations", option = "C"
    ) + 
    theme_bw()
    # facet_wrap(~ Attribute)
```

## EDA - Binary

```{r}
x <- tipsBin |> 
    group_by(Attribute, TF) |> 
    summarise(
        meanDist = mean(distance),
        medianDist = median(distance),
        nTF = length(TF),
        val = unique(mcc_mean),
        nTips = unique(ltp_bp_phys),
        perTips = unique(ltp_bp_phys)
    ) |> 
    ungroup() |> 
    pivot_wider(
        names_from = "TF", values_from = c("nTF", "meanDist", "medianDist")
    ) |> 
    mutate(TFrat = nTF_TRUE / nTF_FALSE) |> 
    mutate(TFratDist = meanDist_TRUE / meanDist_FALSE) |>
    mutate(TFratDistMed = medianDist_TRUE / medianDist_FALSE)
```



```{r}
x |> 
    bind_rows(sumMulG) |> 
    ggplot(aes(nTips, val)) +
    geom_smooth(method = "lm", formula = y ~ x) +
    geom_point(
        aes(size = TFrat, color = TFratDistMed)
    ) +
    scale_color_viridis_c(option = "C") +
    geom_text_repel(aes(label = Attribute)) +
    theme_bw()
```

## Session information


```{r}
sessioninfo::session_info()
```


